### ISSUE TITLE
Urgent: Modules not outputting

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/of-course#658] opened 2015-01-09 13:49 UTC
@msf4-unikent @eg270-unikent @lrhm-unikent 

Hi All, there seems to be a problem with the v-pos modules not outputting on the UG course pages. See for example:

http://www.kent.ac.uk/courses/undergraduate/75/biological-anthropology

Please could this be looked at? 

Thanks

Angela

**Comment by aw285-unikent** [comment] 2015-01-13 14:07
@eg270-unikent @msf4-unikent @lrhm-unikent  Also affecting PGT as reported by KBS. Please could you let me know when this is likely to be fixed? This one is very urgent.

**Comment by eg270-unikent** [comment] 2015-01-13 14:19
Hi @aw285-unikent I'm currently investigating this issue, will let you know whether I have identified the cause as soon as possible.

**Comment by eg270-unikent** [comment] 2015-01-13 17:01
Hi @aw285-unikent I've reran the task but unfortunately modules aren't coming through. I'm going to speak with Server Infrastructure tomorrow morning to discuss permissions issues we have experienced since the server migration last week, where I think the problem is that the cron task user is unable to write to various locations on the new server.

**Comment by aw285-unikent** [comment] 2015-01-13 17:55
@eg270-unikent thanks for the update Edele. I am getting a few queries so I might have to send an update tomorrow to the programmes plant editors if we think it's going to take a bit of time to fix - but I will wait until you've heard from Server Infrastructure first.

**Comment by eg270-unikent** [comment] 2015-01-14 10:45
Hi Angela, unfortunately the person we need to speak to in Server Infrastructure has gone home. He's going to work from home, so hopefully this issue will get sorted today. In light of this, I believe we should update the programme plant editors to let them know that we are having issues with modules.

**Comment by eg270-unikent** [comment] 2015-01-19 10:48
This was due to the caching issues on the new server and was fixed on Friday 16th Jan

**Closed by eg270-unikent** 2015-01-19 10:48 UTC
Labels: Priority:high, Story - In Progress
