### ISSUE TITLE
Heritage management modules not showing

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/of-course#619] opened 2014-10-23 11:00 UTC
@lrhm-unikent 
Modules are not showing on heritage management even though they were recently added by SECL:
http://www.kent.ac.uk/courses/postgraduate/301/heritage-management

Can't see any reason for this in the backend. Please could this be invesitgated today or tomorrow?
Thanks
Angela

**Comment by eg270-unikent** [comment] 2015-01-09 12:45
For reference this seems to be a duplicate of FP#569553. The issue seems to be the c_campus being blank in SDS (also in the handbook editor there is a column headed 'timetabled' which was displaying 'No' for this module) - Gemma Eves thinks this is correct but SSDT seems to think this is causing the modules not to show on the course pages

**Comment by gjmh-unikent** [comment] 2015-01-09 13:55
@eg270-unikent I am not sure these errors/ommisions are related, as this programme is now working as expected localy. i suspect it may be related to a caching issue with regards to the campus identifiers being added/changed. am investigating on www-test.

**Comment by eg270-unikent** [comment] 2015-01-22 14:50
Hi @aw285-unikent I've forced the module cache to regenerate for this course now and am seeing modules on the live frontend.

Can this issue be closed?

**Comment by eg270-unikent** [comment] 2015-01-22 14:52
Also for reference, you can use the following URL if modules are missing for other courses:

https://webtools.kent.ac.uk/programmes/command/modulerefresh/2015/postgraduate/301

Where 301 is the programmes plant ID. You'll need to be logged into programmes plant first though or it won't work.

**Closed** 2015-01-30 15:49 UTC
Labels: bug, Priority:high, Story - Done
